runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /stylesheet
  static_dir: stylesheet
- url: /.*
  script: main.app
- url: /images
  static_dir: images


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
