application: userapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheet
  static_dir: stylesheet
- url: /videos
  static_dir: videos
- url: /images
  static_dir: images
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
